import { NextPage } from 'next';
import Head from 'next/head';
import { Flex, Heading } from '@chakra-ui/react';

import PokemonSelector from '../components/PokemonSelector';
import SelectedPokemon from '../components/SelectedPokemon';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Flex flexDirection='column' height='100vh'>
        <Flex justifyContent='center' alignItems='center'>
          <Heading as='h1' size='3xl' mt='4'>
            PokéFight
          </Heading>
        </Flex>

        <Flex
          justifyContent='center'
          alignItems='center'
          height='100%'
          direction='column'
        >
          <SelectedPokemon />
          <PokemonSelector />
        </Flex>
      </Flex>
    </div>
  );
};

export default Home;
